[versions]
# https://developer.android.com/build/releases/gradle-plugin
android-agp = "8.13.1"

# https://developer.android.com/tools/releases/platforms
android-minSdk = "26"
android-targetSdk = "36"

# https://developer.android.com/jetpack/androidx/releases/activity
androidx-activity-compose = "1.11.0"

# https://developer.android.com/jetpack/androidx/releases/camera
androidx-camera = "1.5.1"

# https://developer.android.com/jetpack/androidx/releases/credentials
androidx-credentials = "1.5.0"

# https://developer.android.com/jetpack/androidx/releases/datastore
androidx-datastore-preferences = "1.1.7"

# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidx-lifecycle = "2.9.4"
androidx-lifecycle-viewmodel-nav3 = "1.0.0-alpha04"

# https://github.com/androidx/media/blob/release/RELEASENOTES.md
androidx-media3 = "1.8.0"

# https://developer.android.com/jetpack/androidx/releases/navigation3
androidx-navigation3 = "1.0.0-rc01"

# https://developer.android.com/jetpack/androidx/releases/test
# androidx-test-espresso-core = "3.7.0"
androidx-test-junit = "1.3.0"

# https://github.com/coil-kt/coil/releases
coil = "3.3.0"

# https://github.com/uzzu/dotenv-gradle/tags
dotenv-gradle = "4.0.0"

# https://developer.android.com/jetpack/androidx/releases/compose-ui
google-fonts-compose = "1.9.4"

# https://developers.google.com/identity/android-credential-manager/releases
google-identity-googleid = "1.1.1"

# https://developers.google.com/ml-kit/vision/text-recognition/v2/android
google-mlkit-text-recognition = "16.0.1"

# https://github.com/kotest/kotest/releases
kotest = "6.0.4"

# https://github.com/JetBrains/kotlin/releases
kotlin = "2.2.21"

# https://github.com/google/ksp/releases
kotlin-ksp = "2.3.2"

# https://github.com/Kotlin/kotlinx.serialization/releases
kotlin-serialization = "1.9.0"

# https://github.com/InsertKoinIO/koin/releases
koin-core = "4.1.1"

# https://github.com/LemonAppDev/konsist/releases
# konsist = "0.17.3"

# https://github.com/ktorio/ktor/releases
ktor = "3.3.2"

# https://github.com/pinterest/ktlint/releases
ktlint-core = "1.7.1"

# https://github.com/mrmans0n/compose-rules/releases
ktlint-compose-rules = "0.4.27"

# https://github.com/jlleitschuh/ktlint-gradle/releases
ktlint-plugin = "13.1.0"

# https://developer.android.com/jetpack/androidx/releases/paging
androidx-paging = "3.4.0-alpha04"

# https://developer.android.com/develop/ui/compose/bom/bom-mapping
compose-bom = "2025.10.01"

# https://developer.android.com/jetpack/androidx/releases/compose-material3#compose_material3_version_15_2
compose-material3-expressive = "1.5.0-alpha08"

# https://junit.org/junit4/
test-junit = "4.13.2"

# https://developer.android.com/jetpack/androidx/releases/room
androidx-room = "2.8.3"

# https://github.com/supabase-community/supabase-kt/releases
supabase-kt = "3.2.6"

# https://github.com/mockk/mockk/releases
mockk = "1.14.6"

[libraries]
# kotlin
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services" }

# Kotest
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

# ktor
ktor-client-engine-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

# others
#konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }
ktlint-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlint-compose-rules" }

# coil
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
coil-network-cache-control = { group = "io.coil-kt.coil3", name = "coil-network-cache-control", version.ref = "coil" }

# Koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin-core" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
# koin-test = { group = "io.insert-koin", name = "koin-test" }
# koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-androidx-startup = { group = "io.insert-koin", name = "koin-androidx-startup" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }

# From compose multiplatform
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test = { module = "androidx.compose.ui:ui-test" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

compose-animation = { module = "androidx.compose.animation:animation" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics" }

compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }

compose-foundation = { module = "androidx.compose.foundation:foundation" }

compose-material = { module = "androidx.compose.material:material" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3-expressive" }
compose-material3-navigation-suite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }

androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore-preferences" }

# room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }

# supabase
supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase-kt" }
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supabase-postgres = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }
supabase-storage = { group = "io.github.jan-tennert.supabase", name = "storage-kt" }
supabase-compose-auth-ui = { group = "io.github.jan-tennert.supabase", name = "compose-auth-ui" }
supabase-compose-coil3 = { group = "io.github.jan-tennert.supabase", name = "coil3-integration" }

# android specific
junit = { group = "junit", name = "junit", version.ref = "test-junit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "google-fonts-compose" }

# mockk
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

# navigation 3
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle-viewmodel-nav3" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-navigation3" }
# camera x
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidx-camera" }
# mlkit
androidx-camera-mlkit-vision = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "androidx-camera" }
text-recognition = { group = "com.google.mlkit", name = "text-recognition", version.ref = "google-mlkit-text-recognition" }
# credentials manager
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "androidx-credentials" }
android-identity-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "google-identity-googleid" }
# optional - needed for credentials support from play services, for devices running Android 13 and below.
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidx-credentials" }
# media3
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidx-media3" }
androidx-media3-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "androidx-media3" }

# paging3
androidx-paging3-common = { group = "androidx.paging", name = "paging-common", version.ref = "androidx-paging" }
androidx-paging3-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidx-paging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
dotenv-gradle = { id = "co.uzzu.dotenv.gradle", version.ref = "dotenv-gradle" }
