name: Build & Release Signed APK

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "jetbrains"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

      - name: Build Signed APK
        run: ./gradlew clean assembleRelease \
          -Pandroid.injected.signing.store.file=release.keystore \
          -Pandroid.injected.signing.store.password=${{ secrets.SIGNING_STORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.SIGNING_KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Save APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download built APK
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: release-apk

      - name: Create GitHub Release (stable)
        uses: softprops/action-gh-release@v2
        if: ${{ !contains(github.ref_name, '-') }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "üöÄ Nueva versi√≥n disponible."
          draft: false
          prerelease: false
          files: release-apk/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        if: ${{ contains(github.ref_name, '-') }}
        with:
          tag_name: ${{ github.ref_name }}
          name: "Pre-release ${{ github.ref_name }}"
          body: "‚öôÔ∏è Versi√≥n beta"
          draft: false
          prerelease: true
          files: release-apk/*.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
